export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOAD_LOGIN_SUCCESS = "LOAD_LOGIN_SUCCESS";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

export const SET_PRENOTATIONS = "SET_PRENOTATIONS";
export const SET_PRENOTATIONS_SUCCESS = "SET_PRENOTATIONS_SUCCESS";

export const SET_LOCATIONS_SEATS = "SET_LOCATIONS_SEATS";
export const SET_LOCATIONS_SEATS_SUCCESS = "SET_LOCATIONS_SEATS_SUCCESS";

export const GET_SEATS = "GET_SEATS";
export const GET_SEATS_SUCCESS = "GET_SEATS_SUCCESS";