export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOAD_LOGIN_SUCCESS = "LOAD_LOGIN_SUCCESS";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";